mkdir ../Logs
mkdir ../Logs/Analysis
mkdir ../Logs/Blasting
mkdir ../Logs/Mapping
mkdir ../Logs/Preprocessing
mkdir ../Logs/Reference_creation
mkdir ../Misc
mkdir ../Misc/Mapping
mkdir ../Misc/Mapping/Bamout
mkdir ../Misc/Mapping/Bamout/Bowtie
mkdir ../Misc/Mapping/Bamout/Bwa
mkdir ../Misc/Mapping/Bamout/Star
mkdir ../Misc/Mapping/Indexed
mkdir ../Misc/Mapping/Samout/Bowtie
mkdir ../Misc/Mapping/Samout/Bwa
mkdir ../Misc/Mapping/Samout/Star
mkdir ../Misc/Preprocessing
mkdir ../Misc/Preprocessing/Deduplicated
mkdir ../Misc/Preprocessing/Demultiplexed
mkdir ../Misc/Preprocessing/Readgrouped
mkdir ../Misc/Preprocessing/Renamed
mkdir ../Misc/Preprocessing
mkdir ../Misc/Reference_creation
mkdir ../Misc/Reference_creation/Clustered
mkdir ../Misc/Reference_creation/Dereplicated
mkdir ../Misc/Reference_creation/Joined
mkdir ../Misc/Reference_creation/Merged
mkdir ../Misc/Reference_creation/Renamed
mkdir ../Misc/Reference_creation/Sorted
mkdir ../Output
mkdir ../Output/Analysis
mkdir ../Output/Analysis/Bowtie
mkdir ../Output/Analysis/Bwa
mkdir ../Output/Analysis/Star
mkdir ../Output/Analysis/Logsummaries
mkdir ../Output/Blasting
mkdir ../Output/Mapping
mkdir ../Output/Mapping/Index
mkdir ../Output/Mapping/Index/Bowtie
mkdir ../Output/Mapping/Index/Bwa
mkdir ../Output/Mapping/Index/Star
mkdir ../Output/Preprocessing
mkdir ../Output/Preprocessing/Barcodesfiltered
mkdir ../Output/Preprocessing/Fastpreports
mkdir ../Output/Preprocessing/Preprocessed
mkdir ../Output/Preprocessing/Preprocessedmonos
mkdir ../Output/Reference_creation
