
# To select which mapper to use, change this to either Bowtie, Bwa of Star. If all mappers should be used 
mapper_mode : "Bowtie"
# This parameter defines the name of the barcode file in the Input folder.
barcode_file: "barcodes.tsv"
# Below, set the location of the Input folder.
input_dir     : "/vol/ribesecology/nielsw"

# -- main folders
output_dir    : "../Output"
tmp_dir       : "../Misc"
sup_dir       : "Supplement" 

# To change the multimap, edit the number after k or c, depending on which mapper(s) should be used. If multimapping should 
# be turned off, this should be an empty string.
multimap_bowtie : ""
multimap_bwa    : ""



# for now, ignore the settings defined below.
# ------------------------------------------------------------------------------------


# ref_mode allows the implementation of an already existing reference. 
# the default is Create where the reference is created from the monos in the input reads
# If the reference is Available ref_mode should be set "present" after which the location of the reference (ref_loc)
# and the location of an csv which has the mapping stats of the monos used for the reference creation in order to do the filtering.
ref_mode : ""
ref_loc : ""
reads_loc : ""
mono_select_loc: ""
# should be divisible by 4 (implementation at a later point)
max_threads: 16
#number of sequencing cycles
pcr_cycles        : 150
#Minimal cluster depth
min-depth: 2
#Location of the blastDB
blastDB: /vol/micro-databases/blast"
# sorteing
min_unique_size : 2

# filters parameters for csv filtering
filter_1: 8
filter_2: 15
filter_3: 1000

# In case the adapters that should be used are different than the ones defined below, 
# change them to the correct adapters.
adapter1: "ATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT" 
adapter2: "CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT"

# In case the STAR mapper is to be used, set the value below to whatever value feels like a sufficient value  for RAM usage in bits.
# A value too low tends to break the entire thing currently, so better to overshoot than to undershooot. The default value should be enough.
star_ram        : 665000000000

